apiVersion: batch/v1
kind: CronJob
metadata:
  name: secrets-backup
  namespace: custom
spec:
  schedule: "*/10 * * * *" # Run every 10 minutes
  jobTemplate:
    metadata:
      labels:
        app: secrets-backup
    spec:
      template:
        metadata:
          labels:
            app: secrets-backup
        spec:
          serviceAccountName: secrets-backup
          restartPolicy: OnFailure
          containers:
            image: ghcr.io/spack/secrets-backup:0.0.1
            imagePullPolicy: IfNotPresent
            name: python-backup-script
            resources:
              requests:
                cpu: 100m
                memory: 1G
          nodeSelector:
            spack.io/node-pool: base
