---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-backup
  namespace: custom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/SecretsBackupRole-production

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-backup
  namespace: custom
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-backup
  namespace: custom
subjects:
  - kind: ServiceAccount
    name: secrets-backup
roleRef:
  kind: Role
  name: secrets-backup
  apiGroup: rbac.authorization.k8s.io
