---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-backup
  namespace: custom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::588562868276:role/SecretsBackupRole-production

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-backup
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-backup
subjects:
  - kind: ServiceAccount
    name: secrets-backup
    namespace: custom
roleRef:
  kind: ClusterRole
  name: secrets-backup
  apiGroup: rbac.authorization.k8s.io
