apiVersion: v1
data:
  gitlab-token: |
    # result of:
    echo -n ${gitlab_token} | base64
kind: Secret
metadata:
  name: gitlab-clear-pipelines
  namespace: custom
  annotations:
    fluxcd.io/ignore: "true"
type: Opaque
