apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../production/karpenter/service-monitor.yaml
- ../../production/karpenter/provisioners/runners/testing/provisioners.yaml
- ../../production/karpenter/provisioners/runners/graviton/2/provisioners.yaml
- ../../production/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml
- ../../production/karpenter/provisioners/gitlab/provisioner.yaml
- ../../production/karpenter/provisioners/beefy/provisioner.yaml
- ../../production/karpenter/provisioners/base/provisioner.yaml
patches:
  - target:
      kind: Provisioner
      name: glr-x86-64-v2
    patch: |-
      - op: replace
        path: /spec/requirements/2/values
        value: ["us-west-1b", "us-west-1c"]

  - target:
      kind: Provisioner
      name: glr-graviton2
    patch: |-
      - op: replace
        path: /spec/requirements/2/values
        value: ["us-west-1b", "us-west-1c"]
