apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-api-scrape
  namespace: custom
spec:
  encryptedData:
    # gitlab access token (get from https://gitlab.spack.io/spack/spack/-/settings/access_tokens)
    gitlab-private-token: AgAR18Q8wtEw8j6tfCilT9YugOOB2ensYNh+L81QWEgQ8HVmXw5IX+NtEZXuEV9IqxxHi9bF09paEryXot8I5r4Ddi3OQNsJZ4Z9MGgbAZuUeF11PN/dB3l1KN0eODG5GI5BkbEMtTGIrTDfZz7K4RSwDAKgFvk/Cufe7Agwk9hAl2bTlDOLTpL6hAvMmHQwDkCRSXqpHQhkFxL0xxhsxVOWrNZnDIMftpFe2qmSk5TkjF1L+C86ichw5g+6GsyrrkRes6lG1jYN5ADVXRn3NllEl5d51ViKaggjve5EwN1J0DSxpDpxiKTy3WjPxJzaDUkTzWNUr3/f1ypKCfPCeVJe3ERXe/hfyKlHnVHrLTatxHXRZ8YJwxq6vUAEdGdoDzLaTtT5QfiyWbHa0ZUvWznBvCwIhQEzrSlOZBdLyRDToOCfP2mB1Al+y4uobu0N3BBVUmHkfoW7WMwliSrFW+VRowG/QvL800pCbjLpoE/reYzcW2tJwMq5BZkomZvTBVne2fpqU65MufWTX2yRL695ojcs3g9ZSY9yn3N5IV7R7q+TJgCxbyIJGfhP7o35hPFLE+3Yejk1rJR3YEPGb5VZHtag40cLX+NEXL9N0jRffi4HPKhBvt7ldImbTdkRymeluLdZZRiTKeb6YBGkt5K3CTHqB6sSCEPz84eHWX0mONGk0zD6H490ND+TVaWHHuhTYHdGuuRdHMjOGjJNTprESoBBu8dkvRdlTQ==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
