apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-api-scrape
  namespace: custom
spec:
  encryptedData:
    # gitlab access token (get from https://gitlab.spack.io/spack/spack/-/settings/access_tokens)
    gitlab-private-token: AgATS0jkZlt8Y/4uphlBhXNqAhXeUOgSbLX9kBmiFYs3p+I1c0Xp6RoXbJPOVTki43j5Ab3ICe7FdJ3AMJa6MsPzQItrmWwVSV1Dwv6VM3HfOuGb2nC6ruDVff8BFf19yATnh/w0ef1uzTVyg61WNnl7HlSl2EH+eRzAGowJkIxSrJD3FjxnhZazKV/OItCm0B4uGCYkkjOYM9VQMltpOW0iyvaseozmKEwqGH2uTDNBoupBeLZHGz8ltOYK6G1SCZt7N4hsHPoBEpKcardgSUH72oySBWULVtt9Em9Y4VQG9mP09AOHqbFO8nRj0rCaQpBMBlZzj9TzpbQCdHJSklyGTAMtzzb5O0CPynwRy52VT6OS36DgMwTlg4gSMPKvNrr+2GIzjQuejhXw4YRKDgr9Fi4F7JpYUVUSYZQcVmkP47ugFLf8JoevlVvbNiM/AV+N8TxNpbIvyuv8QXsN1aLkCZmidJT5NwFjV+tdkhinFjcpc02TKiDC/oQuJFdgVatvqhp792jOtJR4A/7e6lBHScIV71hPJRouK2IuQdcxfWmhrc4pjPFbe5iOvZDUsSEZwsrNnMgFpehDHBu7DUJHkGufJREU9dai9VwSES0NSCV7SWmKUh5OULvd2j32YXKCU62FBa5fG5jUlPhiCQJynCdiBVL1G3lwa98taCcT018tP58wMgi2z4Ijaqx94cme64W+1CvMd3skKbC1PKrzmOfRjdFMUUK8dA==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
      creationTimestamp: null
      name: gitlab-api-scrape
      namespace: custom
