# TODO: If gitlab node-pool is ever migrated to karpenter, delete this file.
# This is still necessary, even with the base node-pool gone, since CAS needs to run somewhere
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  releaseName: cluster-autoscaler
  chart:
    name: cluster-autoscaler
    repository: https://kubernetes.github.io/autoscaler
    version: 9.9.2  # cluster-autoscaler@1.20.0
  values:
    cloudProvider: aws
    awsRegion: us-east-1
    autoDiscovery:
      clusterName: spack
      tags:
      - k8s.io/cluster-autoscaler/enabled
      - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}
      - kubernetes.io/cluster/{{ .Values.autoDiscovery.clusterName }}

    extraArgs:
      balance-similar-node-groups: true
      leader-elect: true
      skip-nodes-with-system-pods: false

    nodeSelector:
      spack.io/node-pool: base

    resources:
      requests:
        cpu: 100m
        memory: 800M

    replicaCount: 3

    serviceMonitor:
      enabled: false
