apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: event-exporter-cfg
  namespace: monitoring
spec:
  encryptedData:
    config.yaml: AgAByM7p5QSAKZOkYAOj6BKvOb5QmbdwA5aCHccXbeFQVR7SexjXUcBdbG288em9vwYBhs2UidTZaeL5XXaaPP9lHCfy/9/1SptCYRz8gPbygwan3cq93NIb/TaCPXwt/D9uXj1BkssE2bQEBXtpgsIH9AaVR4U1wn1nd1UnHfZk43vE4FL+LcFdFmkvKHThvsYFSgHwm1Z9lWWYY7wqKacoyfqkqK237yFr+vOK2uJ3YAWaTkZtDK20j5MpD+FNK0dR/FUU8HXFoo1upiyEMSZ06fvYpErq227RuiFsngEUa7Jj91U6SU5CBWJm6GuvW5SjeMI8xLo2LzKcYAYEyzNhXVrX+PIf5CT86ng8wYKKnAf8JZqSq3Kugl8P89Ve7acID0UlcutS0k+LvoaOfWRb6HbmHIZXo5+TkhKjTwZ0hQ/c2DNl/+e7b6OLAhM8hDUnlPR1YmoxaGI4+0okE4e/nSOhafSMvvISrgT2CcqaGbrVVwytWNiPgc2wM6Q4bDHNhrNExnWu3K173KEQ59b2o6APzb1Gbk96XvwMnY2Q1I0qXxsTgX521f7/8DtL9JQrTjoq2lFQ693qkHtDdzNnegsCpMfQqkad2Hho0fM0B0oHz2ZKEewX1aJw6fX+6NYrTBEw3A1bLpx+pzEXTCdtqWX7Ea5VcHkSc57He3uWXTfwQ+PeElfzj0qO4CneYq+qg+/xOKr3pv4v1w22VYo5yctj+xkl3kisSC8Bt6sbYvBwQawVt68RqhC6+cusIi8YnRCK85pZ2GT6m4yYoukDGCxoKufCGgO8A3rJSJU+M5ppRunBFyEIiMod8c0Y37ZuawBVg7JK5SEOgpJgNLxRONXmNzE+Zmi3PYba/0kRAcX2GZD9fQZC6RCfxXVVDob0Z6tiU5MIYJlWTpSJl0XcrfclPeBCIsDHuzycg3rrlyWTdXVOmvaoPefRgKLFnevSCCnW904Z+OgKkTGRWKIaS0W4szHIULP/vH3VyfB3e1j2kjJdN0rwybQM9W2F/w5dgg3Yn4yC7YimKokNFj+9wyPlkjYBrc+a114QjxDks5ds0WK/PKt4Tx+dZ1sW27d2hmHtkhoQ9x9mGaHGzN9FKqk9X694fqG1Z8CifnhlOkhH2fy7gQUq/w6NqNB3KQ0k8rMl735FHba/fF1Zj3hTGfDnXSTIYJI+lC4zRwsdwLa+5dUq3B/cEQ+simxAIzLO4oYN9Xh6oLRzS2v/N7phyTcrIfG5npb3ZsxUDVZ/UhcA2ecWxsqN9OHuyUFjfx88+/3vnDt6G7G+HR2ELEhZfOLd1VV1EkeG5p5wx3hFFFLrP61vbah02O6/ak2kb3iT30aVaXawsjrvl2lFD9Xj1prAABVCETAduvGNtvdUsKsLB4Uvd04cruxGctKqsIQd1VoeN9THcPPmpRCzJgO7BCbDZeT0XA5uCczDdQWhwzmUNEQVMSgDc83hYw9gUXJqNGy/uUky+/aQSfgUNRi/JS7APnz4rGDD7r0C0Xf/fzqb73C1XTcXX28T5jvvaw6cJoRJQbhM8IyVAiMP3R18T2mdeXXG6ZOGAEJ/XO/FOcE84enCIQ54J0ntCaiwG28Pl69GcNQ/cY47nZQCfzRtd4X07EXLH0HPn2a0j0s1O2PkAMqJ6cGs7mUT+JPVFH/eQ/hEOHIKTS0DuRK7rvrtW/97L5HGhQfMwUxOxJYWMaLFVCp8vQRqzL4Ya7GBDfFwFpZAysC/IBu+wDyka+OmkMI=
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
      creationTimestamp: null
      name: event-exporter-cfg
      namespace: monitoring
    type: Opaque
