---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-staging-webservice-patch
  namespace: gitlab
  annotations:
    cd.spack.io/staged-resource: "1"
data:
  apiVersion: cert-manager.io/v1
  kind: Certificate
  name: gitlab-webservice
  patch: |
    - op: replace
      path: /metadata/name
      value: gitlab-{ENV}-webservice
    - op: replace
      path: /spec/secretName
      value: tls-gitlab-{ENV}-webservice
    - op: replace
      path: /spec/dnsNames/0
      value: gitlab.{ENV}.spack.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-staging-registry-patch
  namespace: gitlab
  annotations:
    cd.spack.io/staged-resource: "1"
data:
  apiVersion: cert-manager.io/v1
  kind: Certificate
  name: gitlab-registry
  patch: |
    - op: replace
      path: /metadata/name
      value: gitlab-{ENV}-registry
    - op: replace
      path: /spec/secretName
      value: tls-gitlab-{ENV}-registry
    - op: replace
      path: /spec/dnsNames/0
      value: registry.gitlab.{ENV}.spack.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-staging-minio-patch
  namespace: gitlab
  annotations:
    cd.spack.io/staged-resource: "1"
data:
  apiVersion: cert-manager.io/v1
  kind: Certificate
  name: gitlab-minio
  namespace: gitlab
  patch: |
    - op: replace
      path: /metadata/name
      value: gitlab-{ENV}-minio
    - op: replace
      path: /spec/secretName
      value: tls-gitlab-{ENV}-minio
    - op: replace
      path: /spec/dnsNames/0
      value: minio.gitlab.{ENV}.spack.io
