---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-packages
  namespace: spack
spec:
  secretName: tls-packages
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - packages.test.spack.io
