# apiVersion: v1
# kind: Secret
# metadata:
#   name: event-exporter-cfg
#   namespace: monitoring
# data:
#   config.yaml: |
#     logLevel: error
#     logFormat: json
#     route:
#       # Main route
#       routes:
#         # This route allows dumping all events because it has no fields to match and no drop rules.
#         - match:
#             - receiver: "runner-events"
#             - namespace: "pipeline|gitlab"
#     receivers:
#       - name: "runner-events"
#         opensearch:
#           hosts:
#             - DEADBEEF
#           index: kube-events
#           indexFormat: "kube-events-{2006-01-02}"
#           username: FOO
#           password: BAR
#           # If set to true, it allows updating the same document in ES (might be useful handling count)
#           useEventID: false
