---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-spackbot
  namespace: spack
spec:
  secretName: tls-spackbot
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: spackbot.test.spack.io
  dnsNames:
    - spackbot.test.spack.io
