# Secret used for creating the gitlab_ro_user with the gitlab_ro_user_job.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-ro-postgresql-password
  namespace: gitlab
spec:
  encryptedData:
    postgresql-gitlab-ro-user-password: AgBFKrud9bcWzlPA4W79ibO4v6u9KLbzujj9ihAVcdCk5bvoOxlM4zgz6Av9yKgwfJZqFqBvnTqAETeYwD7l8VXQVrzNSwh8oI0iXHj1fQvL3S4ITuiWJj8U0bQMGh43I0tRcrtyTuhJz4J6ahH40QG8GmaegZolrRrqeoQsoftSK2Xrbq4YIGP6cP8NaY42oY6mwKUckKiMFn4GEFEAmbsLlrU/8BGw462qUtI5MjLjiKNRpVmP9DLRUqKBs3FVD3ObzQPhWXzlohx4fzC77UxPKVofuoY8YppP0TrcFRu4EwPeyUE3pVKu0UDCzCvAJxT1koQOCKsbzvgCThZGunF+uuUnAkIukgJgduwYrmiPMzwJpHIYasYdOUcD5S8ghXe9a6w2tT8zz9PLcgEQUTJGWq0BisOHTN8xCBoN7oHcxenidq/NIGCq3mG8Yik9YXZfUyo8viLLhcQHcKthPwDg/0mVpgp8ucO2kzHOo0X3VdV0zYGbNXrfuk2qhaiOONOvevf9P6aPai+b1qHa/DwN+C0blL9FBhUJy1suc2FMwhlYJzzH29cXQJ4XBn0nHKzhzzTosTqRkjL+aXpNFB50j0VG9ToM3HD5tVECUKbXOc++EV6k20ReKOkqNMMY6AWMNkhmuYOrBTeNmJ/YvIq8am+7s2O2j4YiIa+iNmCKbXqYkSSF6SdNl9qOeLRtj61xusigoKffvPULYJwjDG4GBBMw1jbIkh04YfX1y82F+eIO4+z5bkkp0Lq2Tjbo/3G59oeHxcktD8sqYbWWUBzx
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
---
# Secret used for setting up the metabase postgres instance's postgres user
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metabase-postgresql-password
  namespace: monitoring
spec:
  encryptedData:
    postgresql-password: AgAKruXqF9l4eet8P5tXVtwJVBPBjpHNhR7yfPlku+N81oH2JJ2gWVN9+dmHKxJ1leTkEKKuPDXp5VobebMk4Dopqdcg6pkpBLLoytnYKLVVxCGSmgyocoKbp2Q/ML55exYfCNDesDfjhI9PUWMwgmkL46+l7dWmlhMimHXSAuwkL3nG/8qOcki3fQLXcuTb0yagV5sgM0h5Qc83NRzqw/OtnZATFeZBQr6K9OEuwHlke+opgguVZGeBDflnOv/HuzgD4VJwsO3aViph/vZEZwGC7tORx/EA6sIuL48LGPngdLVoOcbwv+idurwyoF1Ccp4ogQj58gI1ejJot07iY0aDig+b9TeLGJkHjxoZtJCOgEEA0I9ANBVEz+18lMOjEjC/dSQNCZnklErdnEZLKbdsQ2Ek44pzoBCtJtCwSb241n2F70QAT7fjC6SjWTAixgcVOdHiOphRnpUxZrTcg5vRgXGa32Hgx8nhlVHhfVfIjyjjoLWRic8Z8Z6F/v4rUSiCbkD12BwXVsbaAmvrASnnCN1QFcWgpOqtwOWh78BpwpjLbtntuJBrgBV4LpTZCnKW27kjfDzf/cfJT8xV7ypINQQRTGlTcaCTHwOaujl/QcWkQXZYboxCjuSmYHlTu0qHJgriDhJmXnFIlJPtsBWJ+9NJS3f7FwhsMm9TB8Z4MU7ZC95ieZ546YW7w34oQMmTQ3XKZ5E+9loy5I0xcvRgoBTmtPiDzBKjbF2N23Wx6UVrOucc2xLOZ5P3ig==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
---
# Secret used to log into the GitLab postgres instance
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-postgresql-secrets
  namespace: monitoring
spec:
  encryptedData:
    gitlab-postgresql-host: AgA20onqLuTGmEsTtSQiLoTYNAjj4MAKEp3zYHJjaTWJgHH/y9Vq/lO7/iEM7YBBm77fEfkrzdAaCx/VEUVB0rmPgoA+qrs98S6BWxyDOahN3Ia4of65ung8EcCXJ/vysz8X3weMHoBhQplcxE5/kEPIKSkNDzBjDId113RPnhHEeb9ug2hwbAqFLaYcewwua1ujys92KIYaWSJfXRWxlvUcLSQvEWhnMnil6G/gUg2KILEF6no5A8JG11STb2drDaNKGVAZtVIr6z22wnaFbVGUJGOwNGETY4h4n7hF75t3upfaT55f+rejhScvFVwwMyIW74WRiXPG79HYbRlBP6mQ9kj0/gwaVJYFv01J60kC2/TqchGtSeA/MPDCWCisrabDp0ZKQSKmm92/vsmt8QmTi8h8yEY6+JycAIo3TY4tyG/VMGOhCgFI6amc4k6dLDciAW+YFBengfAXFSyWZs8xkTQc1dN/rVl1hAd+BJekp3Na7LhGIKCVFAykXJ/RjaCRaE6Ya5W61MPvLzSsKzPA3AQG1IwdDzvKXNq7duAS8eHZ6pa9fhd5kkRvhWHvP4Wk6ttczuZDNi3Y31A5CVRB06UirWFevxhhqCn9mnz8Mwroixzh3Hqqw78EMzwnCGq9CI2RkK5Dh0QJad6x1B6Oql4pcPhOrSkHnvx1Al63SKbNpE4yTVR7PyxrVCKHyf2a6irMy0pazwSwfjw6LJiICiLKchO8ftidCtjIqAj5AzlVrMAt7SkFXmyK8cPnjqWHqNGhc93WOnHQ
    gitlab-postgresql-password: AgDNgNMMfOzRIsHtisRZXW9ezfe+95wFvVQnYzBhyQgFXQo9y9W2vjBArzSqnv1GNW2i+4d6HDtqsaW3BmSPfFQn5ePR8apFmWdpPrnoJ4EwUsSK5olhVGL+euRpaGQ5kwYfGOJTt+ZC+BUYe/TO2bXGyodypywNmru5OqecT4FqAhdJZcEbc0CASeys+/g9H9Et3KZn0MrT6q6NZC+NCLDvDypZ/2SD9VOHsr+CrHexJ77Re7uiuMG3G5ZH/PHgchIR3SOpsu+gfJyA40YmFaXaWpoFCjuEAzo+3UathTc/4Xskb3F5pndXZCCjx441T2r0G+tN4yNmDqTDnQojZIkv3bmlZlEMtkz1ZHcjktlufXcJbNE3WP3VTCDazjN9fgezyJbjrVVFsJ+ZiOyDjAwMlTFazgvLJc+M1WLEVcT0yAwJH1b1yUgIGDzeVea4M9QFZD+VrwnuYO0f9XeEevsLkne5oEb5/yka4/o7otU5Sb0AFxBxhZq30k/ZxYcRzHMmual+vQZXcgIMYi5kv7jZC9C/GzEvyXEL/LyKWq/oUIdmYMKJLgLvAauDsKmj1YcbHiaM97rCx5TjbF185t+kYHa8Tk/jIP8H1JOBI9xph6CV3Qv9HKXIFTBOgCEDLB3lAn4veNjdOC13k7iDkgW0wgfKAh1nAkIevJVLDbg1hdm/zRQ8+GPLIGAWcPDdPv3vE3+UgUER0DpX3mVLYxE1rdJp1Q==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
