# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: slack-webhook-alertmanager
#   namespace: monitoring
#   annotations:
#       fluxcd.io/ignore: "true"
# data:
#   webhook: DEADBEEF  # fake-secret

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     fluxcd.io/ignore: "true"
#   name: kube-prometheus-stack-grafana
#   namespace: monitoring
# data:
#   admin-password: DEADBEEF # fake-secret
#   admin-user: DEADBEEF # fake-secret
#   ldap-toml: ""

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     fluxcd.io/ignore: "true"
#   name: grafana-github-oauth-client
#   namespace: monitoring
# data:
#   client-id: DEADBEEF # fake-secret
#   client-secret: DEADBEEF # fake-secret
