apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rotate-keys
  namespace: custom
spec:
  encryptedData:
    # gitlab access token (get from https://gitlab.spack.io/spack/spack/-/settings/access_tokens)
    gitlab-token: AgBzbKGovVMRbwY09oIyM3k/LAFWeCTsXgrabwGTA7zm+cfueaY82FfXjB6+HRrL11+oH1k9OWxfdfqRDvSB7brqsryazG5MVoADo7G6ma++kqa94EiD4AgvAp/UbRCdeXcMs5YXMH/Q8djPCRH16g3Lqh+dQcK8UkGUunGAw+75iMvMFOjhcCQrJeGE71YidDrA7ImtlZncJ//VOm62SouV82W5m5C6ARxvpIhSYHdo2gkVdXcMh8F5xQjxVuhfuSaw14WLwxhrAD2RhQ6OF92qsd4+DSPP3OGpfH0a1uz2FrAU/btitcUGz8PuskkA32lm2KlVYFVP219RDnI3zVdYpMZaHfI2lkJiBniPGashUF6bpj4jpr5B9aaumB0i19gy5sgQwBKQn53syXh9ImyHEG75rt5Bx5KATj/2M2+gohqRWsl2yeQCJX/s7T+Jfo7ltaoakikblYfw/wkYZeGy3YJBozCJLpjScZfNaozM7Wkj9bKXcsfH13TfyB4KPeB+wdtx8wc0NqsW6OPgHCm3nTY/wjlBXxtowKooIndDLESFagOYzb/l+nHl/5BNhL08CiDsAN+UjZ/JZfgIGI1rkuyxcrVwi8kHIi1IvX735bs/pDmH+NooN5VFP3JZmjNoR78C29sTC1zkfnAN6dZCF5OOoRS3H49k/0ggxxF56NdlSnZXhnQn8JTehYI5VhNil0sz4F2s9exibyDQTH+HxSb7DLHtstahQA==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
