apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-clear-pipelines
  namespace: custom
spec:
  encryptedData:
    gitlab-token: AgBqnRLOWmR10Kz14GwEQG9V0dK4ugFMLwGdngakfq0egykVP5CvSX226qiKTIXXdoz2GMuEHmrSWRQ8485B6Em/8Y+jyY+KTpvBjQ0lATfkbnIfHLyrOSwrlOvGcrZkOkprsjzbnoGRj5GvWn43k6bSrNjovdjKY40aFdYS8fjRjZurimGwzMdYbSALmxHcaFi98gmtl9DLdAB5QIQrxwBWTVRTDdmZmeKnLq51SNUJX6EqUm/BaR2T7VyehNHWSaxpFjP0Q/yMWVxVNRZsutENUkbZ0d0xZMfn9aGx3dibWkrFNxY5DN+tIT74uyGDmfZkEcDmE0G/LGUIwvC+7qBQ+b8Fl8730XOrZi6tqfdxfP0y4tbdiqm4mBhs+iJ4/Z7YqDhG1oHN9fy81YXIH7LhCRleBxvIrTAtpG35UZoVrlNDrP12jXo5QTqfeRwzBtPJ1TCacEKyXoBoK434bwpStnr/dvcxcTSh0LFPXLUrse0caY4FOk+Vz2asKbEEWlNbqYtRGIIrpEePHf2jbXFZm1HKM7+cSYYBwUz9uRCx5tlyYKE/slX56E+SCdhBJ8wvSJPOTcodm7UZGz2LwbQK2BMYYmLHkpbuBJidk7+oBVkIQE/vKeyIqS7AXEojYIvfQtz5/in1lC/jaKIclLwlJEazj8PC4GsqohvbEUVH+EXsHVglOwLup5MeQNSGm2fiKss+qFJ8KwblMgM0gtSjjUKiGyI6s3+PCQ==
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/reconcile: disabled
        sealedsecrets.bitnami.com/managed: "true"
