apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../production/ingress-nginx/namespace.yaml
- ../../production/ingress-nginx/release.yaml
- ../../production/ingress-nginx/oauth2-proxy.yaml
patches:
  - target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
    patch: |-
      - op: replace
        path: /spec/values/controller/autoscaling/maxReplicas
        value: 1
      - op: replace
        path: /spec/values/defaultBackend/replicaCount
        value: 1

  - target:
      kind: Deployment
      name: oauth2-proxy
      namespace: ingress-nginx
    patch: |-
      - op: replace
        path: /spec/containers/0/args
        value:
        - --github-org spack
        - --github-user danlamanna
        - --provider=github
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --redirect-url=https://prometheus.staging.spack.io/oauth2/callback

      - op: replace
        path: /spec/containers/0/env/0/value
        value: 5346c6b5d5bea71fb115
