---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: index-binary-caches
  namespace: custom
spec:
  schedule: "0 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: index-binary-caches
          restartPolicy: Never
          containers:
          - name: index-binary-caches
            image: ghcr.io/spack/cache-indexer:0.0.1
            imagePullPolicy: IfNotPresent
          nodeSelector:
            spack.io/node-pool: base
