---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aws-node-termination-handler
  namespace: kube-system
spec:
  releaseName: aws-node-termination-handler
  chart:
    name: aws-node-termination-handler
    repository: https://aws.github.io/eks-charts
    version: 0.18.0  # aws-node-termination-handler@1.16.0
  values:
    # emitKubernetesEvents If true, Kubernetes events will be emitted
    # when interruption events are received and when actions are taken on
    # Kubernetes nodes. In IMDS Processor mode a default set of
    # annotations with all the node metadata gathered from IMDS will be
    # attached to each event
    emitKubernetesEvents: true
    enablePrometheusServer: true
    prometheusServerPort: 9092

    resources:
      requests:
        cpu: 10m
        memory: 200M
