---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-slack
  namespace: spack
spec:
  secretName: tls-slack
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: slack.spack.io
  dnsNames:
    - slack.spack.io
