---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-metabase
  namespace: monitoring
spec:
  secretName: tls-metabase
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: metabase.test.spack.io
  dnsNames:
    - metabase.test.spack.io
