---
apiVersion: v1
kind: Secret
metadata:
  name: rotate-keys
  namespace: custom
  annotations:
    fluxcd.io/ignore: "true"
data:
  gitlab-token: "" # gitlab access token (get from https://gitlab.spack.io/spack/spack/-/settings/access_tokens)
